// Mocks generated by Mockito 5.0.16 from annotations
// in converssor_moedas/test/modules/home/infra/repositories/currency_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:converssor_moedas/modules/home/infra/datasources/models/currency_info_models.dart'
    as _i2;
import 'package:converssor_moedas/modules/home/infra/repositories/datasources/currency_datasource_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCurrencyInfoModel_0 extends _i1.Fake
    implements _i2.CurrencyInfoModel {}

/// A class which mocks [ICurrencyDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockICurrencyDataSource extends _i1.Mock
    implements _i3.ICurrencyDataSource {
  MockICurrencyDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CurrencyInfoModel> getCurrencies() => (super.noSuchMethod(
          Invocation.method(#getCurrencies, []),
          returnValue:
              Future<_i2.CurrencyInfoModel>.value(_FakeCurrencyInfoModel_0()))
      as _i4.Future<_i2.CurrencyInfoModel>);
  @override
  String toString() => super.toString();
}
