name: converssor_moedas
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  flutter_modular: ^4.2.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  intl: ^0.17.0
  localization: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  modular_test: ^1.0.1+1
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
