// Mocks generated by Mockito 5.0.16 from annotations
// in converssor_moedas/test/modules/home/domain/usecases/convert_currency_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:converssor_moedas/modules/home/domain/entities/currency_info_entity.dart'
    as _i2;
import 'package:converssor_moedas/modules/home/domain/repositories/currency_repository_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCurrencyInfoEntity_0 extends _i1.Fake
    implements _i2.CurrencyInfoEntity {}

/// A class which mocks [ICurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICurrencyRepository extends _i1.Mock
    implements _i3.ICurrencyRepository {
  MockICurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CurrencyInfoEntity> getCurrencies() => (super.noSuchMethod(
          Invocation.method(#getCurrencies, []),
          returnValue:
              Future<_i2.CurrencyInfoEntity>.value(_FakeCurrencyInfoEntity_0()))
      as _i4.Future<_i2.CurrencyInfoEntity>);
  @override
  String toString() => super.toString();
}
