// Mocks generated by Mockito 5.0.16 from annotations
// in converssor_moedas/test/modules/home/presentation/pages/home/home_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:converssor_moedas/commons/adapters/http_client/http_response.dart'
    as _i2;
import 'package:converssor_moedas/commons/adapters/http_client/interfaces/http_client_adapter.dart'
    as _i3;
import 'package:flutter/material.dart' as _i6;
import 'package:flutter_modular/src/presenter/models/modular_navigator.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeHttpResponse_0 extends _i1.Fake implements _i2.HttpResponse {}

/// A class which mocks [IHttpClientAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHttpClientAdapter extends _i1.Mock
    implements _i3.IHttpClientAdapter {
  MockIHttpClientAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse> get(String? path,
          {Map<String, dynamic>? queryParameters,
          Map<String, dynamic>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [path],
                  {#queryParameters: queryParameters, #headers: headers}),
              returnValue:
                  Future<_i2.HttpResponse>.value(_FakeHttpResponse_0()))
          as _i4.Future<_i2.HttpResponse>);
  @override
  _i4.Future<_i2.HttpResponse> post(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          Map<String, dynamic>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers
              }),
              returnValue:
                  Future<_i2.HttpResponse>.value(_FakeHttpResponse_0()))
          as _i4.Future<_i2.HttpResponse>);
  @override
  _i4.Future<_i2.HttpResponse> put(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          Map<String, dynamic>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers
              }),
              returnValue:
                  Future<_i2.HttpResponse>.value(_FakeHttpResponse_0()))
          as _i4.Future<_i2.HttpResponse>);
  @override
  _i4.Future<_i2.HttpResponse> delete(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          Map<String, dynamic>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers
              }),
              returnValue:
                  Future<_i2.HttpResponse>.value(_FakeHttpResponse_0()))
          as _i4.Future<_i2.HttpResponse>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [IModularNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockIModularNavigator extends _i1.Mock implements _i5.IModularNavigator {
  MockIModularNavigator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  _i4.Future<T?> push<T extends Object?>(_i6.Route<T>? route) =>
      (super.noSuchMethod(Invocation.method(#push, [route]),
          returnValue: Future<T?>.value()) as _i4.Future<T?>);
  @override
  _i4.Future<T?> popAndPushNamed<T extends Object?, TO extends Object?>(
          String? routeName,
          {TO? result,
          Object? arguments,
          bool? forRoot = false}) =>
      (super.noSuchMethod(
          Invocation.method(#popAndPushNamed, [routeName],
              {#result: result, #arguments: arguments, #forRoot: forRoot}),
          returnValue: Future<T?>.value()) as _i4.Future<T?>);
  @override
  _i4.Future<T?> pushNamed<T extends Object?>(String? routeName,
          {Object? arguments, bool? forRoot = false}) =>
      (super.noSuchMethod(
          Invocation.method(#pushNamed, [routeName],
              {#arguments: arguments, #forRoot: forRoot}),
          returnValue: Future<T?>.value()) as _i4.Future<T?>);
  @override
  _i4.Future<T?> pushNamedAndRemoveUntil<T extends Object?>(
          String? newRouteName, bool Function(_i6.Route<dynamic>)? predicate,
          {Object? arguments, bool? forRoot = false}) =>
      (super.noSuchMethod(
          Invocation.method(#pushNamedAndRemoveUntil, [newRouteName, predicate],
              {#arguments: arguments, #forRoot: forRoot}),
          returnValue: Future<T?>.value()) as _i4.Future<T?>);
  @override
  _i4.Future<T?> pushReplacementNamed<T extends Object?, TO extends Object?>(
          String? routeName,
          {TO? result,
          Object? arguments,
          bool? forRoot = false}) =>
      (super.noSuchMethod(
          Invocation.method(#pushReplacementNamed, [routeName],
              {#result: result, #arguments: arguments, #forRoot: forRoot}),
          returnValue: Future<T?>.value()) as _i4.Future<T?>);
  @override
  void pop<T extends Object?>([T? result]) =>
      super.noSuchMethod(Invocation.method(#pop, [result]),
          returnValueForMissingStub: null);
  @override
  bool canPop() =>
      (super.noSuchMethod(Invocation.method(#canPop, []), returnValue: false)
          as bool);
  @override
  _i4.Future<bool> maybePop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(Invocation.method(#maybePop, [result]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  void popUntil(bool Function(_i6.Route<dynamic>)? predicate) =>
      super.noSuchMethod(Invocation.method(#popUntil, [predicate]),
          returnValueForMissingStub: null);
  @override
  void navigate(String? path, {dynamic arguments}) => super.noSuchMethod(
      Invocation.method(#navigate, [path], {#arguments: arguments}),
      returnValueForMissingStub: null);
  @override
  void setObserver(List<_i6.NavigatorObserver>? navigatorObservers) =>
      super.noSuchMethod(Invocation.method(#setObserver, [navigatorObservers]),
          returnValueForMissingStub: null);
  @override
  void setNavigatorKey(_i6.GlobalKey<_i6.NavigatorState>? navigatorkey) =>
      super.noSuchMethod(Invocation.method(#setNavigatorKey, [navigatorkey]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
}
